export const cols = [
  {title: 'No.'},
  {title: 'ID Vendedor'},
  {title: 'Nombre'},
  {title: 'Teléfono'},
  {title: 'E-mail'},
  {title: 'Rol Usuario'},
  {title: 'Sueldo'}
]


export const rows = [
  {
    id: 1,
    idEmployee: "e01",
    name: "Geroniomo Uc",
    phone: "55 8367 0580",
    email: "hola@gmail.com",
    userRole: "vendedor",
    salary: 500,
  },
  {
    id: 2,
    idEmployee: "e01",
    name: "Geroniomo Uc",
    phone: "55 8367 0580",
    email: "hola@gmail.com",
    userRole: "vendedor",
    salary: 500,
  },
  {
    id: 1,
    idEmployee: "e01",
    name: "Geroniomo Uc",
    phone: "55 8367 0580",
    email: "hola@gmail.com",
    userRole: "vendedor",
    salary: 500,
  },
  {
    id: 3,
    idEmployee: "e01",
    name: "Geroniomo Uc",
    phone: "55 8367 0580",
    email: "hola@gmail.com",
    userRole: "vendedor",
    salary: 500,
  },
  {
    id: 4,
    idEmployee: "e01",
    name: "Geroniomo Uc",
    phone: "55 8367 0580",
    email: "hola@gmail.com",
    userRole: "vendedor",
    salary: 500,
  },
  {
    id: 5,
    idEmployee: "e01",
    name: "Geroniomo Uc",
    phone: "55 8367 0580",
    email: "hola@gmail.com",
    userRole: "vendedor",
    salary: 500,
  },
  {
    id: 6,
    idEmployee: "e01",
    name: "Geroniomo Uc",
    phone: "55 8367 0580",
    email: "hola@gmail.com",
    userRole: "vendedor",
    salary: 500,
  },
  {
    id: 7,
    idEmployee: "e01",
    name: "Geroniomo Uc",
    phone: "55 8367 0580",
    email: "hola@gmail.com",
    userRole: "vendedor",
    salary: 500,
  },
  {
    id: 8,
    idEmployee: "e01",
    name: "Geroniomo Uc",
    phone: "55 8367 0580",
    email: "hola@gmail.com",
    userRole: "vendedor",
    salary: 500,
  },
  {
    id: 9,
    idEmployee: "e01",
    name: "Geroniomo Uc",
    phone: "55 8367 0580",
    email: "hola@gmail.com",
    userRole: "vendedor",
    salary: 500,
  },
  {
    id: 10,
    idEmployee: "e01",
    name: "Geroniomo Uc",
    phone: "55 8367 0580",
    email: "hola@gmail.com",
    userRole: "vendedor",
    salary: 500,
  }
]
