export const cols = [
  {id: 'idNumberLeads', label: 'No.'},
  {id: 'nameLeads', label: 'Nombre'},
  {id: 'phoneLeads', label: 'Teléfono'},
  {id: 'numberPeopleLeads', label: 'No. Personas'},
  {id: 'numberPetsLeads', label: 'No. Mascotas'},
  {id: 'dateRegistration', label: 'Fecha Registro'},
  {id: 'dateStart', label: 'Fecha Inicio'},
  {id: 'dateEnd', label: 'Fecha Fin'},
  {id: 'advance', label: 'Anticipo'},
  {id: 'stateLeads', label: 'Estado'},
  {id: 'idEmployee', label: 'ID Vendedor'},
  {id: 'idIcons'},
]


export const rows = [
  {
    idNumberLeads: 1,
    nameLeads: "Geroniomo Uc",
    phoneLeads: "55 8367 0580",
    numberPeopleLeads: 5,
    numberPetsLeads: 0,
    dateRegistration: "5/Agosto/2021",
    dateStart: "10/Agosto/2021",
    dateEnd: "12/Agosto/2021",
    advance: 650,
    stateLeads: "Checando",
    idEmployee: "e01",
  },
  {
    idNumberLeads: 2,
    nameLeads: "Geroniomo Uc",
    phoneLeads: "55 8367 0580",
    numberPeopleLeads: 5,
    numberPetsLeads: 0,
    dateRegistration: "5/Agosto/2021",
    dateStart: "10/Agosto/2021",
    dateEnd: "12/Agosto/2021",
    advance: 650,
    stateLeads: "Checando",
    idEmployee: "e01",
  },
  {
    idNumberLeads: 3,
    nameLeads: "Geroniomo Uc",
    phoneLeads: "55 8367 0580",
    numberPeopleLeads: 5,
    numberPetsLeads: 0,
    dateRegistration: "5/Agosto/2021",
    dateStart: "10/Agosto/2021",
    dateEnd: "12/Agosto/2021",
    advance: 650,
    stateLeads: "Checando",
    idEmployee: "e01",
  },
  {
  idNumberLeads: 4,
  nameLeads: "Geroniomo Uc",
  phoneLeads: "55 8367 0580",
  numberPeopleLeads: 5,
  numberPetsLeads: 0,
  dateRegistration: "5/Agosto/2021",
  dateStart: "10/Agosto/2021",
  dateEnd: "12/Agosto/2021",
  advance: 650,
  stateLeads: "Checando",
  idEmployee: "e01",
},
{
  idNumberLeads: 5,
  nameLeads: "Geroniomo Uc",
  phoneLeads: "55 8367 0580",
  numberPeopleLeads: 5,
  numberPetsLeads: 0,
  dateRegistration: "5/Agosto/2021",
  dateStart: "10/Agosto/2021",
  dateEnd: "12/Agosto/2021",
  advance: 650,
  stateLeads: "Checando",
  idEmployee: "e01",
},
{
  idNumberLeads: 6,
  nameLeads: "Geroniomo Uc",
  phoneLeads: "55 8367 0580",
  numberPeopleLeads: 5,
  numberPetsLeads: 0,
  dateRegistration: "5/Agosto/2021",
  dateStart: "10/Agosto/2021",
  dateEnd: "12/Agosto/2021",
  advance: 650,
  stateLeads: "Checando",
  idEmployee: "e01",
},
{
  idNumberLeads: 7,
  nameLeads: "Geroniomo Uc",
  phoneLeads: "55 8367 0580",
  numberPeopleLeads: 5,
  numberPetsLeads: 0,
  dateRegistration: "5/Agosto/2021",
  dateStart: "10/Agosto/2021",
  dateEnd: "12/Agosto/2021",
  advance: 650,
  stateLeads: "Checando",
  idEmployee: "e01",
},
{
  idNumberLeads: 8,
  nameLeads: "Geroniomo Uc",
  phoneLeads: "55 8367 0580",
  numberPeopleLeads: 5,
  numberPetsLeads: 0,
  dateRegistration: "5/Agosto/2021",
  dateStart: "10/Agosto/2021",
  dateEnd: "12/Agosto/2021",
  advance: 650,
  stateLeads: "Checando",
  idEmployee: "e01",
},
{
  idNumberLeads: 9,
  nameLeads: "Geroniomo Uc",
  phoneLeads: "55 8367 0580",
  numberPeopleLeads: 5,
  numberPetsLeads: 0,
  dateRegistration: "5/Agosto/2021",
  dateStart: "10/Agosto/2021",
  dateEnd: "12/Agosto/2021",
  advance: 650,
  stateLeads: "Checando",
  idEmployee: "e01",
},
{
  idNumberLeads: 10,
  nameLeads: "Geroniomo Uc",
  phoneLeads: "55 8367 0580",
  numberPeopleLeads: 5,
  numberPetsLeads: 0,
  dateRegistration: "5/Agosto/2021",
  dateStart: "10/Agosto/2021",
  dateEnd: "12/Agosto/2021",
  advance: 650,
  stateLeads: "Checando",
  idEmployee: "e01",
},
]